services:
  myits-be:
    container_name: myits-openid-sso
    restart: always
    build:
      context: .
      target: dependencies
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    volumes:
      - ./:/home/node/app
      # Uncomment the below line if you're developing on MacOS
      - /home/node/app/node_modules
    environment:
      NODE_OPTIONS: '--inspect=0.0.0.0'
    command: dumb-init node ace serve --watch
    depends_on:
      myits-db:
        condition: service_healthy

  myits-db:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER}']
      interval: 10s
      timeout: 5s
      retries: 5

  myits-adminer:
    image: adminer
    container_name: adminer
    ports:
      - '8080:8080'
    depends_on:
      - myits-db

volumes:
  postgres-data:
